# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hulo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhulo.proto\x12\x04Hulo\" \n\x11\x43ompletionRequest\x12\x0b\n\x03str\x18\x01 \x01(\t\"5\n\x12\x43ompletionResponse\x12\x1f\n\x08suggests\x18\x01 \x03(\x0b\x32\r.Hulo.Suggest\"=\n\x07Suggest\x12\x0c\n\x04Text\x18\x01 \x01(\t\x12\x13\n\x0b\x44\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07\x43omment\x18\x03 \x01(\x08\"(\n\x0b\x43\x61llRequest\x12\x0c\n\x04\x46unc\x18\x01 \x01(\t\x12\x0b\n\x03\x41rg\x18\x02 \x01(\t\"\'\n\x0c\x43\x61llResponse\x12\n\n\x02Ok\x18\x01 \x01(\x08\x12\x0b\n\x03\x42uf\x18\x02 \x01(\t2\x7f\n\rHuloInterface\x12?\n\nCompletion\x12\x17.Hulo.CompletionRequest\x1a\x18.Hulo.CompletionResponse\x12-\n\x04\x43\x61ll\x12\x11.Hulo.CallRequest\x1a\x12.Hulo.CallResponseB\x16\n\x04huloZ\x07./;hulo\xaa\x02\x04hulob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hulo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\004huloZ\007./;hulo\252\002\004hulo'
  _COMPLETIONREQUEST._serialized_start=20
  _COMPLETIONREQUEST._serialized_end=52
  _COMPLETIONRESPONSE._serialized_start=54
  _COMPLETIONRESPONSE._serialized_end=107
  _SUGGEST._serialized_start=109
  _SUGGEST._serialized_end=170
  _CALLREQUEST._serialized_start=172
  _CALLREQUEST._serialized_end=212
  _CALLRESPONSE._serialized_start=214
  _CALLRESPONSE._serialized_end=253
  _HULOINTERFACE._serialized_start=255
  _HULOINTERFACE._serialized_end=382
# @@protoc_insertion_point(module_scope)
