# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hulo_pb2 as hulo__pb2


class HuloInterfaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Completion = channel.unary_unary(
                '/Hulo.HuloInterface/Completion',
                request_serializer=hulo__pb2.CompletionRequest.SerializeToString,
                response_deserializer=hulo__pb2.CompletionResponse.FromString,
                )
        self.Call = channel.unary_unary(
                '/Hulo.HuloInterface/Call',
                request_serializer=hulo__pb2.CallRequest.SerializeToString,
                response_deserializer=hulo__pb2.CallResponse.FromString,
                )


class HuloInterfaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Completion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HuloInterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Completion': grpc.unary_unary_rpc_method_handler(
                    servicer.Completion,
                    request_deserializer=hulo__pb2.CompletionRequest.FromString,
                    response_serializer=hulo__pb2.CompletionResponse.SerializeToString,
            ),
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=hulo__pb2.CallRequest.FromString,
                    response_serializer=hulo__pb2.CallResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Hulo.HuloInterface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HuloInterface(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Completion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Hulo.HuloInterface/Completion',
            hulo__pb2.CompletionRequest.SerializeToString,
            hulo__pb2.CompletionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Hulo.HuloInterface/Call',
            hulo__pb2.CallRequest.SerializeToString,
            hulo__pb2.CallResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
